#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys: []
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
runcmd:
  - mkdir -p /var/run/sshd
  - sudo echo "PermitRootLogin no" >> /etc/ssh/sshd_config
  - sudo echo "AllowUsers ubuntu" >> /etc/ssh/sshd_config
  - sudo echo "AuthorizedKeysCommand none" >> /etc/ssh/sshd_config
  - sudo echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
  - sudo echo "ListenAddress 0.0.0.0" >> /etc/ssh/sshd_config
  - sudo echo "TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem" >> /etc/ssh/sshd_config
  - sudo service ssh restart
  - sudo echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7GNS20k0WsH+B6sEqElKQCh5gSvCUyjW695dbQbJn3/j3S2r3CZadmTqJDA0feBEhq1aqWCRUyFiv93/1Ns/Gw0DgeZu9UTBJhHE3nmhp1b+xK3ci9/KebFWqPHBB0IF6ZdXz04x7b2msDytusaBrCChusdekgZWboiZG/1Xa0nLHg/QVysz1GkytquKVkMy0lvKb6tc6ZQRJRAbyL6nOU8PkqEITHalC43GN8qtzWT8h5VxiVksn22UEnWuHICrkLBFk7u83QLO4BzV4l7bv5GdaU3VowDvJOuRgBO0EQblJ1BIQ0UsMKrG8HepFAUBzffTCNM/TxUAjeu0YxTbRf3mBrENQV7ewV63Qqbx7m00FS9Wc8E34peYKMUd0llH1RnNiYTD3UTGnN6rNxaLCY9flSdws7gE7H7HnpT14jC/jI/FzIUgRyvzPwcs0iJBEXufKMFUo26rPFQ0a7WSYjBji9gQFqeEDuy80WExXIjGwtsI08aY4ILz1Jzatp2da6WQKmMoMOlN+sEFUcB+kUYjqdeZJ8nDzy2eNioyqIG8J9Wvb5H7p0IHn8D5jqhg/rtVNNMIBNYdRI2aD50FNvYdRvMlSel6ZnnpfPy7Mb3t2wbKiNm4nlsGH7hRab/Uw4fS1Dy3EK2SF9ZyxiSj7Qdcqz9CzcM/dkulmOLW5Kw==" > /etc/ssh/trusted-user-ca-keys.pem

