---
- name: Install Vault on target hosts
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - wget
          - gnupg
          - software-properties-common
        state: present

    - name: Add HashiCorp GPG key
      shell: |
        wget -O - https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      args:
        executable: /bin/bash
      changed_when: false

    - name: Add HashiCorp repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        tee /etc/apt/sources.list.d/hashicorp.list
      args:
        executable: /bin/bash
      changed_when: false

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Vault
      apt:
        name: vault
        state: present

    - name: Verify Vault installation
      command: vault --version
      register: vault_version_output

    - name: Display Vault version
      debug:
        msg: "Installed Vault version: {{ vault_version_output.stdout }}"
